name = "cloudflare-workers-test"
type = "javascript"
zone_id = "899746401968b9da56bf2e86d94adad3"
account_id = "19fbc3afa40daca99965456c784468e2"
route = ""
workers_dev = true
compatibility_date = "2021-10-28"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
