name = "cloudflare-workers-test"
type = "javascript"
account_id = "19fbc3afa40daca99965456c784468e2"
workers_dev = true
compatibility_date = "2021-10-28"

[build]
command = "yarn install --frozen-lockfile && yarn build"

[build.upload]
format = "service-worker"

[dev]
port = 4000